#!/usr/bin/env bash

## install ansible on ubuntu

sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

## pull ansible
# sudo ansible-pull -U git@github.com:cdcloud-io/ansible-local.git
